[build]
  publish = "dist"
  command = "npm install && npx expo export --platform web --clear"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyDyeIgBxyp3zmfUakFXUQUMNhSBKGBHmkE"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "conn3ctr-fce52.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "conn3ctr-fce52"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "conn3ctr-fce52.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "144936221659"
  REACT_APP_FIREBASE_APP_ID = "1:144936221659:web:efdfea531c7a45d96e85fe"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200