[build]
  publish = "dist"
  command = "npm install && npx expo export --platform web"

[build.environment]
  NODE_VERSION = "18"
  # Add your Firebase environment variables here
  # REACT_APP_FIREBASE_API_KEY = "your-api-key"
  # REACT_APP_FIREBASE_AUTH_DOMAIN = "your-project-id.firebaseapp.com"
  # REACT_APP_FIREBASE_PROJECT_ID = "your-project-id"
  # REACT_APP_FIREBASE_STORAGE_BUCKET = "your-project-id.appspot.com"
  # REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "your-sender-id"
  # REACT_APP_FIREBASE_APP_ID = "your-app-id"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200